public enum Code {
    SUCCESS,
    SHELF_SUBJECT_MISMATCH_ERROR,
    BOOK_NOT_IN_INVENTORY_ERROR,
    BOOK_ALREADY_CHECKED_OUT_ERROR,
    READER_DOESNT_HAVE_BOOK_ERROR,
    READER_COULD_NOT_REMOVE_BOOK_ERROR
}